export const MEDIA_HEADERS: Record<string, string> = {
  '渠道': 'channel',
  '日期': 'recordDate',
  '时间': 'recordDate',
  '统计日期': 'recordDate',
  '报告日期': 'recordDate',
  'Date': 'recordDate',
  'Day': 'recordDate',
  '计划id': 'campaignId',
  '计划ID': 'campaignId',
  '广告计划id': 'campaignId',
  '广告计划ID': 'campaignId',
  '广告系列 ID': 'campaignId',
  '广告系列ID': 'campaignId',
  'Campaign ID': 'campaignId',
  'Campaign Id': 'campaignId',
  'CampaignId': 'campaignId',
  '品种/名称（选填）': 'campaignName',
  '品种/名称': 'campaignName',
  '计划名称': 'campaignName',
  '广告计划名称': 'campaignName',
  '广告系列名称': 'campaignName',
  'Campaign Name': 'campaignName',
  'Campaign': 'campaignName',
  '曝光': 'impressions',
  '曝光量': 'impressions',
  '展示': 'impressions',
  '展示数': 'impressions',
  '展示次数': 'impressions',
  'Impressions': 'impressions',
  '点击': 'clicks',
  '点击量': 'clicks',
  '点击次数': 'clicks',
  'Clicks': 'clicks',
  '花费': 'cost',
  '消耗': 'cost',
  '支出': 'cost',
  'Spend': 'cost',
  'Cost': 'cost',
  '下载': 'downloads',
  '下载量': 'downloads',
  '下载次数': 'downloads',
  'Downloads': 'downloads',
}
